export type Category = 'technical' | 'mental' | 'physical' | 'goalkeeping' | 'positions' | 'traits' | 'hidden'
export type FieldValue = string | number | boolean
export type Values = Record<string, FieldValue | undefined>

export type FieldDef = {
  key: string
  label: string
  category: Category
  min: number
  max: number
}

export const fieldDefs: FieldDef[] = [
  { key: 'ca', label: '현재 능력', category: 'hidden', min: 1, max: 200 },
  { key: 'pa', label: '잠재 능력', category: 'hidden', min: 1, max: 200 },
  { key: 'current_rep', label: '현재 명성', category: 'hidden', min: 0, max: 10000 },
  { key: 'home_rep', label: '국내 명성', category: 'hidden', min: 0, max: 10000 },
  { key: 'world_rep', label: '세계 명성', category: 'hidden', min: 0, max: 10000 },
  { key: 'height', label: '키', category: 'hidden', min: 0, max: 250 },
  { key: 'left_foot', label: '왼발', category: 'hidden', min: 1, max: 20 },
  { key: 'right_foot', label: '오른발', category: 'hidden', min: 1, max: 20 },
  { key: 'morale', label: '사기', category: 'hidden', min: 1, max: 20 },
  { key: 'condition', label: '몸 상태', category: 'hidden', min: 0, max: 10000 },
  { key: 'match_sharpness', label: '경기 감각', category: 'hidden', min: 0, max: 10000 },
  { key: 'fatigue', label: '피로도', category: 'hidden', min: 0, max: 10000 },
  { key: 'dirtiness', label: '더티 플레이', category: 'hidden', min: 1, max: 20 },
  { key: 'consistency', label: '꾸준함', category: 'hidden', min: 1, max: 20 },
  { key: 'important_matches', label: '중요 경기', category: 'hidden', min: 1, max: 20 },
  { key: 'injury_proneness', label: '부상 빈도', category: 'hidden', min: 1, max: 20 },
  { key: 'versatility', label: '다재다능', category: 'hidden', min: 1, max: 20 },
  { key: 'adaptability', label: '적응력', category: 'hidden', min: 1, max: 20 },
  { key: 'ambition', label: '야망', category: 'hidden', min: 1, max: 20 },
  { key: 'loyalty', label: '충성심', category: 'hidden', min: 1, max: 20 },
  { key: 'pressure', label: '압박감 대처', category: 'hidden', min: 1, max: 20 },
  { key: 'professionalism', label: '프로의식', category: 'hidden', min: 1, max: 20 },
  { key: 'sportsmanship', label: '스포츠맨십', category: 'hidden', min: 1, max: 20 },
  { key: 'temperament', label: '참을성', category: 'hidden', min: 1, max: 20 },
  { key: 'controversy', label: '논쟁성', category: 'hidden', min: 1, max: 20 },
  { key: 'corners', label: '코너킥', category: 'technical', min: 1, max: 20 },
  { key: 'crossing', label: '크로스', category: 'technical', min: 1, max: 20 },
  { key: 'dribbling', label: '드리블', category: 'technical', min: 1, max: 20 },
  { key: 'finishing', label: '골 결정력', category: 'technical', min: 1, max: 20 },
  { key: 'first_touch', label: '퍼스트 터치', category: 'technical', min: 1, max: 20 },
  { key: 'free_kick_taking', label: '프리킥', category: 'technical', min: 1, max: 20 },
  { key: 'heading', label: '헤더', category: 'technical', min: 1, max: 20 },
  { key: 'long_shots', label: '중거리 슛', category: 'technical', min: 1, max: 20 },
  { key: 'long_throws', label: '롱 스로인', category: 'technical', min: 1, max: 20 },
  { key: 'marking', label: '마크', category: 'technical', min: 1, max: 20 },
  { key: 'passing', label: '패스', category: 'technical', min: 1, max: 20 },
  { key: 'penalty_taking', label: '페널티 킥', category: 'technical', min: 1, max: 20 },
  { key: 'tackling', label: '태클', category: 'technical', min: 1, max: 20 },
  { key: 'technique', label: '개인기', category: 'technical', min: 1, max: 20 },
  { key: 'aggression', label: '적극성', category: 'mental', min: 1, max: 20 },
  { key: 'anticipation', label: '예측력', category: 'mental', min: 1, max: 20 },
  { key: 'bravery', label: '대담성', category: 'mental', min: 1, max: 20 },
  { key: 'composure', label: '침착성', category: 'mental', min: 1, max: 20 },
  { key: 'concentration', label: '집중력', category: 'mental', min: 1, max: 20 },
  { key: 'decisions', label: '판단력', category: 'mental', min: 1, max: 20 },
  { key: 'determination', label: '승부욕', category: 'mental', min: 1, max: 20 },
  { key: 'flair', label: '천재성', category: 'mental', min: 1, max: 20 },
  { key: 'leadership', label: '리더십', category: 'mental', min: 1, max: 20 },
  { key: 'off_the_ball', label: '오프 더 볼', category: 'mental', min: 1, max: 20 },
  { key: 'positioning', label: '위치 선정', category: 'mental', min: 1, max: 20 },
  { key: 'teamwork', label: '팀워크', category: 'mental', min: 1, max: 20 },
  { key: 'vision', label: '시야', category: 'mental', min: 1, max: 20 },
  { key: 'work_rate', label: '활동량', category: 'mental', min: 1, max: 20 },
  { key: 'acceleration', label: '순간 속도', category: 'physical', min: 1, max: 20 },
  { key: 'agility', label: '민첩성', category: 'physical', min: 1, max: 20 },
  { key: 'balance', label: '균형 감각', category: 'physical', min: 1, max: 20 },
  { key: 'jumping_reach', label: '점프 거리', category: 'physical', min: 1, max: 20 },
  { key: 'natural_fitness', label: '타고난 체력', category: 'physical', min: 1, max: 20 },
  { key: 'pace', label: '주력', category: 'physical', min: 1, max: 20 },
  { key: 'stamina', label: '지구력', category: 'physical', min: 1, max: 20 },
  { key: 'strength', label: '몸싸움', category: 'physical', min: 1, max: 20 },
  { key: 'aerial_reach', label: '공중 장악력', category: 'goalkeeping', min: 1, max: 20 },
  { key: 'command_of_area', label: '장악력', category: 'goalkeeping', min: 1, max: 20 },
  { key: 'communication', label: '수비 조율', category: 'goalkeeping', min: 1, max: 20 },
  { key: 'eccentricity', label: '돌발 행동', category: 'goalkeeping', min: 1, max: 20 },
  { key: 'handling', label: '핸들링', category: 'goalkeeping', min: 1, max: 20 },
  { key: 'kicking', label: '킥', category: 'goalkeeping', min: 1, max: 20 },
  { key: 'one_on_ones', label: '일대일 방어', category: 'goalkeeping', min: 1, max: 20 },
  { key: 'punching', label: '펀칭 빈도', category: 'goalkeeping', min: 1, max: 20 },
  { key: 'reflexes', label: '반사 신경', category: 'goalkeeping', min: 1, max: 20 },
  { key: 'rushing_out', label: '뛰쳐나가기', category: 'goalkeeping', min: 1, max: 20 },
  { key: 'throwing', label: '던지기', category: 'goalkeeping', min: 1, max: 20 },
]

export const positions = [
  { key: 'pos_st', label: '스트라이커', x: 50, y: 8 },
  { key: 'pos_aml', label: '왼쪽 윙어', x: 18, y: 24 },
  { key: 'pos_amc', label: '공격형 미드필더', x: 50, y: 26 },
  { key: 'pos_amr', label: '오른쪽 윙어', x: 82, y: 24 },
  { key: 'pos_ml', label: '왼쪽 미드필더', x: 18, y: 44 },
  { key: 'pos_mc', label: '중앙 미드필더', x: 50, y: 45 },
  { key: 'pos_mr', label: '오른쪽 미드필더', x: 82, y: 44 },
  { key: 'pos_dm', label: '수비형 미드필더', x: 50, y: 62 },
  { key: 'pos_wbl', label: '왼쪽 윙백', x: 10, y: 70 },
  { key: 'pos_wbr', label: '오른쪽 윙백', x: 90, y: 70 },
  { key: 'pos_dl', label: '왼쪽 수비수', x: 20, y: 82 },
  { key: 'pos_dc', label: '중앙 수비수', x: 50, y: 84 },
  { key: 'pos_dr', label: '오른쪽 수비수', x: 80, y: 82 },
  { key: 'pos_gk', label: '골키퍼', x: 50, y: 94 },
]

export const traitGroups = [
  {
    title: '온 더 볼',
    traits: [
      ['trait_cuts_inside_both', '양쪽 측면에서 중앙으로 침투'],
      ['trait_cuts_inside_left', '왼쪽 측면에서 중앙으로 침투'],
      ['trait_cuts_inside_right', '오른쪽 측면에서 중앙으로 침투'],
      ['trait_knocks_past', '공을 차놓고 상대를 제치는 것을 선호'],
      ['trait_runs_rarely', '공을 드물게 드리블'],
      ['trait_runs_often', '공을 자주 드리블'],
      ['trait_run_left', '왼쪽 측면 돌파 선호'],
      ['trait_run_right', '오른쪽 측면 돌파 선호'],
      ['trait_run_center', '경기장 중앙으로 드리블함'],
      ['trait_stops_play', '공을 가지면 잠시 멈추는 플레이 선호'],
      ['trait_crosses_early', '얼리 크로스'],
    ],
  },
  {
    title: '오프 더 볼',
    traits: [
      ['trait_arrives_late', '필요 시 상대 페널티 박스에 한 박자 늦게 침투하는 것을 선호'],
      ['trait_comes_deep', '공을 받기 위해 포지션보다 내려옴'],
      ['trait_gets_forward', '가능할 때마다 최전방으로 침투 선호'],
      ['trait_gets_into_area', '페널티 박스 안으로 침투 선호'],
      ['trait_hugs_line', '터치라인을 따라 움직이는 것을 선호'],
      ['trait_break_offside_trap', '오프사이드 트랩 돌파를 선호'],
      ['trait_moves_channels', '수비수와 풀백 사이로 침투'],
      ['trait_no_moves_channels', '수비수와 풀백 사이 침투를 자제'],
      ['trait_one_twos', '2대1 패스 선호'],
      ['trait_back_to_goal', '골문을 등지는 것을 선호'],
      ['trait_stays_back', '항상 후방에 있는 것을 선호'],
    ],
  },
  {
    title: '패스',
    traits: [
      ['trait_dictates_tempo', '템포 조절 선호'],
      ['trait_switch_flank', '공을 반대편 측면으로 보내는 것을 선호'],
      ['trait_pass_not_score', '득점보다는 패스하는 것을 선호'],
      ['trait_no_through_balls', '스루 패스 하지 않는 것을 선호'],
      ['trait_short_simple_passes', '짧고 간단한 패스 선호'],
      ['trait_killer_balls', '스루 패스를 자주 시도'],
      ['trait_long_passes', '긴 패스를 자주 시도'],
      ['trait_long_throw_counters', '역습을 시작할 때 장거리 스로인 사용'],
    ],
  },
  {
    title: '골 결정력',
    traits: [
      ['trait_overhead_kicks', '오버헤드킥을 시도'],
      ['trait_fk_power', '프리킥 시 강력한 슛 선호'],
      ['trait_lob_keeper', '골키퍼 넘기는 슛 선호'],
      ['trait_round_keeper', '골키퍼를 제치는 것을 선호'],
      ['trait_places_shots', '정확한 슛 선호'],
      ['trait_no_long_shots', '중거리 슛 자제'],
      ['trait_shoots_distance', '중거리 슛 선호'],
      ['trait_shoots_power', '강력한 슛 선호'],
      ['trait_first_time_shots', '빠른 박자에 슛을 자주 시도'],
      ['trait_long_free_kicks', '먼 거리에서 프리킥 시 슛을 자주 시도'],
    ],
  },
  {
    title: '규율',
    traits: [
      ['trait_winds_up', '상대 선수를 거칠게 대하는 것을 선호'],
      ['trait_gets_crowd_going', '관중들을 열광시키는 행동 선호'],
      ['trait_argues_officials', '심판과 언쟁하는 것을 선호'],
    ],
  },
  {
    title: '수비',
    traits: [
      ['trait_dives_tackles', '슬라이딩 태클 선호'],
      ['trait_no_dives_tackles', '슬라이딩 태클을 하지 않는 것을 선호'],
      ['trait_marks_tightly', '상대 선수를 단단히 마크'],
    ],
  },
  {
    title: '개인기',
    traits: [
      ['trait_avoids_weaker_foot', '약한 발을 사용하지 않는 것을 선호'],
      ['trait_curls_ball', '휘어차는 슛 선호'],
      ['trait_dwells_ball', '공을 오래 소유하는 것을 선호'],
      ['trait_long_flat_throw', '빠르고 낮게 깔리는 스로인 구사'],
      ['trait_play_out_trouble', '위기 상황을 벗어나기 위해 개인기를 자주 시도'],
      ['trait_brings_ball_out', '수비 진영에서 드리블하기'],
      ['trait_beat_man_repeatedly', '상대를 여러 차례 속이는 것을 선호'],
      ['trait_tries_tricks', '현란한 개인기를 자주 시도'],
      ['trait_ball_into_feet', '패스를 발밑으로 받는 것을 선호'],
      ['trait_outside_foot', '아웃프론트킥 선호'],
      ['trait_plays_ball_feet', '발로 공을 다룸'],
      ['trait_right_foot_dribble', '드리블 전 오른발 사용을 선호'],
      ['trait_left_foot_dribble', '드리블 전 왼발 사용을 선호'],
    ],
  },
] as const

export const visibleReadKeys = [
  ...fieldDefs.filter((field) => field.category !== 'hidden').map((field) => field.key),
  ...positions.map((position) => position.key),
  ...traitGroups.flatMap((group) => group.traits.map((trait) => trait[0])),
]

export const mockValues: Values = {
  ca: 142,
  pa: 168,
  current_rep: 6350,
  home_rep: 6100,
  world_rep: 5800,
  height: 181,
  left_foot: 12,
  right_foot: 20,
  morale: 15,
  condition: 9400,
  match_sharpness: 8700,
  fatigue: 600,
  dirtiness: 8,
  consistency: 14,
  important_matches: 16,
  injury_proneness: 7,
  versatility: 13,
  adaptability: 12,
  ambition: 16,
  loyalty: 11,
  pressure: 15,
  professionalism: 17,
  sportsmanship: 13,
  temperament: 14,
  controversy: 5,
  corners: 10,
  crossing: 13,
  dribbling: 15,
  finishing: 16,
  first_touch: 14,
  free_kick_taking: 11,
  heading: 12,
  long_shots: 12,
  long_throws: 8,
  marking: 8,
  passing: 13,
  penalty_taking: 13,
  tackling: 8,
  technique: 15,
  aggression: 11,
  anticipation: 14,
  bravery: 12,
  composure: 15,
  concentration: 13,
  decisions: 13,
  determination: 17,
  flair: 16,
  leadership: 10,
  off_the_ball: 15,
  positioning: 9,
  teamwork: 12,
  vision: 14,
  work_rate: 14,
  acceleration: 16,
  agility: 15,
  balance: 13,
  jumping_reach: 10,
  natural_fitness: 14,
  pace: 16,
  stamina: 13,
  strength: 11,
  aerial_reach: 7,
  command_of_area: 6,
  communication: 8,
  eccentricity: 4,
  handling: 7,
  kicking: 9,
  one_on_ones: 6,
  punching: 5,
  reflexes: 8,
  rushing_out: 7,
  throwing: 6,
  pos_st: 20,
  pos_aml: 18,
  pos_amc: 16,
  pos_amr: 15,
  pos_ml: 13,
  pos_mc: 14,
  pos_mr: 12,
  pos_dm: 8,
  pos_wbl: 6,
  pos_wbr: 5,
  pos_dl: 4,
  pos_dc: 5,
  pos_dr: 4,
  pos_gk: 1,
  trait_moves_channels: true,
  trait_dictates_tempo: true,
  trait_places_shots: true,
  trait_comes_deep: false,
  trait_run_left: false,
  trait_run_right: true,
  trait_long_passes: false,
}
